name: Sync and Update Submodules

# This workflow runs in the Parent Repository (conbotics.github.io)
# It is triggered by the 'repository_dispatch' event sent from the cb_docs submodule.
on:
  repository_dispatch:
    types: [submodule-update-needed]

# Permissions: We only need 'contents: read' since we are NOT pushing a commit.
permissions:
  contents: read 

jobs:
  sync_and_update:
    runs-on: ubuntu-latest
    
    # Define these parameters once at the job level
    env:
      REPO_OWNER: conbotics

    steps:
    - name: Generate GitHub App token for Read access
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.DOCS_APP_ID }}
        private-key: ${{ secrets.DOCS }}
        owner: ${{ env.REPO_OWNER }}
        repositories: 'conbotics.github.io, cb_docs'
        
        permissions: |
          contents: read

    - name: Checkout Parent Repository Code (Full Clone)
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        # FIX 1: Perform a full clone (depth 0) to resolve "repository has to be local" error
        fetch-depth: 0 
        submodules: false # We will handle submodules manually

    - name: Authenticate, Sync, and Update Submodules
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        # --- Authentication Fix ---
        # Inject the token into the submodule URL for authentication. 
        # This allows 'git submodule update' to fetch private repositories.
        git config --global url."https://x-access-token:$GH_TOKEN@github.com".insteadOf "https://github.com"

        # 1. Sync: Ensures the .gitmodules config is up-to-date with remote URLs
        git submodule sync
        
        # 2. Update: Initializes the submodule (if needed) and checks out the SHA recorded 
        #    in the parent repository's current HEAD commit.
        git submodule update --init --recursive
        
        # --- Cleanup ---
        # Remove the temporary token injection from the global config
        git config --global --unset-all url."https://x-access-token:$GH_TOKEN@github.com".insteadOf
        
    # --- Build Steps ---
    - name: Install MkDocs and Dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Build MkDocs Documentation
      run: |
        mkdocs build --clean
